server:
  port: 8080

app:
  endpoints:
    flightData: flightsData

spring:
  cloud:
    config:
      allowOverride: true
  resources:
    add-mappings: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flights

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka